/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee
Title: Python
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const ReactLogo = (props) => {
  const groupRef = useRef()
  
  // Add gentle floating animation
  useFrame((state) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005
    }
  })

  return (
    <Float floatIntensity={2}>
      <group ref={groupRef} {...props} scale={0.1}>
        <PythonModel />
      </group>
    </Float>
  )
}

const PythonModel = (props) => {
  const { nodes, materials } = useGLTF('/python.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Python_Python_0.geometry}
          material={materials.Python}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/python.glb')

export default ReactLogo;
